title: Hello, world! I'm Kartik Raj Pari
description: > # this means to ignore newlines until "baseurl:"
permalink: ':title/'
baseurl: '/blog' # the subpath of your site, e.g. /blog
url: "https://kartikpari.github.io" # the base hostname & protocol for your site, e.g. http://example.com

# Author Settings
author: Kartik Raj Pari # add your name
author-img: Lastride.jpg # add your photo
about-author: Anything in life worth doing is worth overdoing. Moderation is for cowards # add description
social-github: kartikpari # add your Github handle
social-linkedin: kartik-raj-pari-221a8179
social-email: kartik.kartikace.raj@gmail.com

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji
  - jekyll-include-cache

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
